In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf 
import sklearn
from tensorflow.python.keras.utils import np_utils

In [92]:
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import accuracy_score


In [93]:
base = pd.read_csv('iris.csv')

In [94]:
base

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [95]:
# Seleciona as colunas de índice 0 a 3 do DataFrame 'base' e armazena os valores em 'x'
X = base.iloc[:, 0:4].values  # A variável 'x' agora contém os dados das quatro primeiras colunas da base, usadas como características de entrada


In [96]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [97]:
# Seleciona a coluna de índice 4 do DataFrame 'base' e armazena os valores em 'y'
y = base.iloc[:, 4].values  # A variável 'y' agora contém os dados da quinta coluna da base, que é usada como rótulo para o modelo


In [98]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [99]:
# Cria uma instância do codificador de rótulos para transformar rótulos de texto em valores numéricos
labelencoder = LabelEncoder()

# Aplica o codificador ao vetor 'y' para converter as classes de rótulos em valores inteiros
y = labelencoder.fit_transform(y)  # Cada rótulo agora é representado por um número único


In [100]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [101]:
# Converte a variável `y` para uma matriz categórica (one-hot encoding)
y = to_categorical(y)  # Define num_classes se necessário

y  # Mostra o valor transformado

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [102]:
# Divide o conjunto de dados em dados de treinamento e teste
# x_train e y_train são usados para treinar o modelo
# x_test e y_test são usados para avaliar a performance do modelo
# test_size=0.25 indica que 25% dos dados serão reservados para teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)


In [103]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112, 3), (38, 3))

In [124]:
# Cria uma nova rede neural sequencial
rede_neural = Sequential([
    # Camada de entrada: recebe dados com 4 características
    tf.keras.layers.InputLayer(shape=(4,)),
    
    # Primeira camada oculta: camada densa com 4 neurônios e função de ativação ReLU
    tf.keras.layers.Dense(units=4, activation='relu'),
    
    # Segunda camada oculta: outra camada densa com 4 neurônios e função de ativação ReLU
    tf.keras.layers.Dense(units=4, activation='relu'),
    
    # Camada de saída: camada densa com 3 neurônios para previsão de classes múltiplas
    # A função de ativação softmax é utilizada para normalizar as saídas entre 0 e 1
    tf.keras.layers.Dense(units=3, activation='softmax')
])


In [105]:
rede_neural.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [126]:
 #Compila o modelo da rede neural
# Define o otimizador como 'adam', a função de perda como 'categorical_crossentropy' para problemas de classificação multiclasse,
# e a métrica como 'categorical_accuracy' para avaliar a acurácia do modelo durante o treinamento
rede_neural.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [115]:
# Treina a rede neural com os dados de treinamento
# X_train e y_train são as variáveis que contêm os dados de entrada e as classes correspondentes
rede_neural.fit(X_train, y_train, batch_size=10, epochs=1500)  # Tamanho do lote de 10 e 1500 épocas

Epoch 1/1500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - categorical_accuracy: 0.9959 - loss: 0.0319
Epoch 2/1500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - categorical_accuracy: 0.9763 - loss: 0.0431
Epoch 3/1500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 775us/step - categorical_accuracy: 0.9726 - loss: 0.0700
Epoch 4/1500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - categorical_accuracy: 0.9949 - loss: 0.0322
Epoch 5/1500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - categorical_accuracy: 0.9811 - loss: 0.0608
Epoch 6/1500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - categorical_accuracy: 0.9577 - loss: 0.0986
Epoch 7/1500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.9718 - loss: 0.0634 
Epoch 8/1500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - categorical_accuracy: 0.9937 - loss: 0.0244
Epoch 9/1500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - categorical_accuracy: 0.9812 - loss: 0.0530
Epoch 10/1500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.9841 - loss: 0.0463 
E

In [117]:
rede_neural.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 1.0000 - loss: 0.0174 


[0.01971522532403469, 1.0]

In [118]:
previsoes = rede_neural.predict(X_test)
print(previsoes)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
[[5.2364879e-10 9.9959689e-01 4.0306459e-04]
 [3.3979496e-14 4.3004312e-02 9.5699573e-01]
 [9.9999654e-01 3.1943716e-06 2.1316282e-07]
 [9.9999344e-01 6.1434512e-06 3.7161220e-07]
 [9.9999964e-01 3.6427187e-07 3.3677800e-08]
 [2.9746915e-21 1.2826860e-03 9.9871731e-01]
 [8.1367915e-20 2.9665371e-04 9.9970335e-01]
 [2.5163609e-13 9.9984872e-01 1.5121544e-04]
 [1.0959240e-16 4.1759312e-02 9.5824075e-01]
 [5.9751497e-09 9.9941921e-01 5.8085966e-04]
 [2.7882963e-09 9.9948198e-01 5.1807280e-04]
 [1.4409614e-20 2.5540825e-03 9.9744594e-01]
 [9.9999380e-01 5.7885768e-06 3.5328836e-07]
 [9.9999619e-01 3.5258320e-06 2.3181934e-07]
 [1.7430313e-21 1.0788174e-04 9.9989212e-01]
 [5.2709365e-10 9.9959654e-01 4.0346134e-04]
 [1.2680402e-21 4.2042750e-04 9.9957961e-01]
 [2.4644228e-10 9.9963999e-01 3.5994849e-04]
 [1.1072008e-12 9.9547088e-01 4.5291693e-03]
 [9.9999964e-01 3.6427187e-07 3.3677800e-08]
 [1.2569609e-22 8.2360239e-05 9.9991763e-01]
 [6.5459378e-13 9

In [119]:
previsoes = previsoes > 0.5
print(previsoes)

[[False  True False]
 [False False  True]
 [ True False False]
 [ True False False]
 [ True False False]
 [False False  True]
 [False False  True]
 [False  True False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False False  True]
 [False  True False]
 [False False  True]
 [False  True False]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [ True False False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False False  True]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [ True False False]
 [False False  True]
 [False False  True]]


In [120]:
y_test2 = [np.argmax(t) for t in y_test]
print(y_test2)

[1, 2, 0, 0, 0, 2, 2, 1, 2, 1, 1, 2, 0, 0, 2, 1, 2, 1, 1, 0, 2, 1, 0, 0, 1, 2, 2, 2, 0, 2, 0, 1, 1, 1, 2, 0, 2, 2]


In [121]:
previsoes2 = [np.argmax(t) for t in previsoes]
print(previsoes2)

[1, 2, 0, 0, 0, 2, 2, 1, 2, 1, 1, 2, 0, 0, 2, 1, 2, 1, 1, 0, 2, 1, 0, 0, 1, 2, 2, 2, 0, 2, 0, 1, 1, 1, 2, 0, 2, 2]


In [122]:
accuracy = accuracy_score(y_test2, previsoes2)
print("Acurácia:", accuracy)

print(y_test2)
print(previsoes2)


Acurácia: 1.0
[1, 2, 0, 0, 0, 2, 2, 1, 2, 1, 1, 2, 0, 0, 2, 1, 2, 1, 1, 0, 2, 1, 0, 0, 1, 2, 2, 2, 0, 2, 0, 1, 1, 1, 2, 0, 2, 2]
[1, 2, 0, 0, 0, 2, 2, 1, 2, 1, 1, 2, 0, 0, 2, 1, 2, 1, 1, 0, 2, 1, 0, 0, 1, 2, 2, 2, 0, 2, 0, 1, 1, 1, 2, 0, 2, 2]


In [123]:
confusion_matrix(y_test2, previsoes2)

array([[11,  0,  0],
       [ 0, 12,  0],
       [ 0,  0, 15]], dtype=int64)